// auth
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOAD_FAIL = 'USER_LOAD_FAIL';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const GET_KEY_SUCCESS = 'GET_KEY_SUCCESS';
export const GET_KEY_FAIL = 'GET_KEY_FAIL';
export const GENERATE_KEY_SUCCESS = 'GENERATE_KEY_SUCCESS';
export const GET_ANALYTICS_SUCCESS = 'GET_ANALYTICS_SUCESS';
export const GET_ANALYTICS_FAIL = 'GET_ANALYTICS_FAIL';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// api
export const GET_PACKAGES_SUCCESS = 'GET_PACKAGES_SUCCESS';
export const GET_PACKAGES_FAIL = 'GET_PACKAGES_FAIL';
export const GET_PACKAGE_SUCCESS = 'GET_PACKAGE_SUCCESS';
export const GET_PACKAGE_FAIL = 'GET_PACKAGE_FAIL';
export const RESET_EMAIL_SUCCESS = 'RESET_EMAIL_SUCCESS';
export const RESET_EMAIL_FAIL = 'RESET_EMAIL_FAIL';
export const REQUEST_UPGRADE_SUCCESS = 'REQUEST_UPGRADE_SUCCESS';
export const REQUEST_UPGRADE_FAIL = 'REQUEST_UPGRADE_FAIL';
export const VERIFY_UPGRADE_SUCCESS = 'VERIFY_UPGRADE_SUCCESS';
export const VERIFY_UPGRADE_FAIL = 'VERIFY_UPGRADE_FAIL';
